version: '3.2'

services:
  db:
    image: postgres:alpine

    env_file: .env

    ports:
      - 5432:5432

    volumes:
      - sql:/docker-entrypoint-initdb.d

    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  app:
    env_file: .env
    
    build: .

    ports: 
      - ${DEPENDENCIES_APP_PORT}:${DEPENDENCIES_APP_PORT}

    volumes:
      - ./key.pem:/app/key.pem
      - sql:/usr/lib/node_modules/@dependencies/app/database

    links:
      - db

    depends_on:
      - db

    environment:
      GITHUB_PRIVATE_KEY_PATH: ./key.pem
      POSTGRES_HOST: db

volumes:
  sql: